language: python
python: 3.6
cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"

stages:
  - linting
  - test

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python - -y --preview
  - source $HOME/.poetry/env
  - poetry config virtualenvs.create false
  - poetry --no-interaction --verbose install

script:
  - pytest

jobs:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      before_script:
        - pip install coveralls
      after_success:
        - coveralls


    - stage: linting
      python: 3.7
      dist: xenial
      install:
        - pip install -U black flake8 flake8-bugbear flake8-todo
      script:
        - black --check --verbose .
        - flake8 warlock
